codecov:
  branch: main
  
coverage:
  range: 60..90
  round: down
  precision: 2

  status:
    project:
      default:
        enabled: yes
        target: 100%
        threshold: 1%
        branches:
          - master
        paths: 
          - "src/yaw"
    patch:
      default:
        target: 100%
        threshold: 1%
        branches: null
