#!/usr/bin/env python3
import argparse
import os

import numpy as np
from astropy.cosmology import default_cosmology
from astropy.io import fits as pyfits

from Nz_Fitting import RedshiftHistogram
from yaw_tools.utils import DEFAULT_CAT_EXT, write_nz_stats
from yet_another_wizz import PdfMaker


parser = argparse.ArgumentParser(
    description='SURPRISE!')
parser.add_argument(
    'nz_file', metavar='NZ_FILE',
    help='FITS table with list of data redshifts')
parser.add_argument(
    '--cat-file-ext', metavar='INT', default=DEFAULT_CAT_EXT,
    help='fits extesion containg data (default: %d)' % DEFAULT_CAT_EXT)
parser.add_argument(
    '--col-spec', metavar='FIELD', required=True,
    help='spectroscopic redshift column name')
parser.add_argument(
    '--col-phot', metavar='FIELD', required=True,
    help='photometric redshift column name')
parser.add_argument(
    '--col-weight', metavar='FIELD',
    help='weight column name')
parser.add_argument(
    '--zbin-keys', nargs="*", required=True,
    help='redshift keys (e.g. 0.101z1.201) used to bin the sample and '
         'name the output files')
parser.add_argument(
    '--n-bins', type=int, default=200,
    help='number of bins to use for the histogram (default: %(default)s)')
parser.add_argument(
    '--bin-type', default="adapt",
    choices=["linear", "adapt", "comoving", "logspace"],
    help='spacing of the spectroscopic bins (default: %(default)s)')
parser.add_argument(
    '-o', '--output',
    help='folder in which the output is stored (optional)')


if __name__ == '__main__':

    args = parser.parse_args()

    setattr(args, "output", os.path.abspath(args.output))
    print("set output folder to %s" % args.output)
    if not os.path.exists(args.output):
        os.makedirs(args.output)

    # load the reference sample
    print("==> loading unknown objects")
    with pyfits.open(args.nz_file) as fits:
        z_spec = fits[args.cat_file_ext].data[args.col_spec]
        z_phot = fits[args.cat_file_ext].data[args.col_phot]
        if args.col_weight is not None:
            weights = fits[args.cat_file_ext].data[args.col_weight]
        else:
            weights = None
    # compute the binning
    if args.bin_type == "linear":
        binning = PdfMaker.linearBins(
            args.n_bins, z_spec.min(), z_spec.max())
    elif args.bin_type == "logspace":
        binning = PdfMaker.logspaceBins(
            args.n_bins, z_spec.min(), z_spec.max())
    elif args.bin_type == "comoving":
        binning = PdfMaker.comovingBins(
            args.n_bins, z_spec.min(), z_spec.max(), default_cosmology.get())
    else:
        binning = PdfMaker.adaptiveBins(
            args.n_bins, None, None, z_spec)

    print("writing histogram statistics to: stats/")
    statdir = os.path.join(args.output, "stats")
    if not os.path.exists(statdir):
        os.mkdir(statdir)
    for zbin in args.zbin_keys:
        outfile = os.path.join(
            args.output,
            os.path.basename(os.path.splitext(args.nz_file)[0]) +
            "_%s" % zbin)
        print(
            "writing histogram data to: {:}.*".format(
                os.path.basename(outfile)))
        # bin the data
        zmin, zmax = [float(f) for f in zbin.split("z")]
        mask = (z_phot >= zmin) & (z_phot < zmax)
        kwargs = {"bins": binning, "density": True}
        if weights is not None:
            kwargs["weights"] = weights[mask]
        z_spec_binned = z_spec[mask]
        counts = np.histogram(z_spec_binned, **kwargs)[0]
        # write the histogram
        nz_hist = RedshiftHistogram(binning, counts)
        nz_hist.write(outfile)
        # write statistics
        write_nz_stats(statdir, nz_hist, zkey=zbin)
