name: Build wheels and sdist and upload to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -U .

    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
