name: coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build-n-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # --editable seems necessary for codecov
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --editable .[test]

      - name: Run tests and coverage
        run: python -m pytest tests --cov=src/ --cov-report=xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
