name: CI

on:
  schedule:
    - cron: 0 6 * * 1

jobs:
  build-n-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies on ${{ matrix.python-version }}
        run: |
          python -m pip install -U pip
          pip install -U .[test]

      - name: Run tests on ${{ matrix.python-version }}
        run: python -m pytest -v
